<?php
/**
 * Caridea
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 * @copyright 2015 LibreWorks contributors
 * @license   http://opensource.org/licenses/Apache-2.0 Apache 2.0 License
 */
namespace Caridea\Http;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-25 at 12:25:34.
 */
class AcceptTypesTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @covers Caridea\Http\AcceptTypes::__construct
     * @covers Caridea\Http\AcceptTypes::preferred
     */
    public function testPreferred1()
    {
        $types = new AcceptTypes(['HTTP_ACCEPT' => "text/html, application/xhtml+xml,application/xml; q=0.9,*/*;q=0.8"]);
        $this->assertEquals('text/html', $types->preferred(['text/css', 'text/html', 'application/javascript']));
        $this->assertEquals('application/xml', $types->preferred(['application/xml', 'text/css', 'application/json']));
        $this->assertEquals('application/json', $types->preferred(['application/json']));
        $this->assertEquals('text/plain', $types->preferred(['text/plain', 'text/css', 'application/json']));
        $this->assertNull($types->preferred([]));
    }
    
    /**
     * @covers Caridea\Http\AcceptTypes::__construct
     * @covers Caridea\Http\AcceptTypes::preferred
     */
    public function testPreferred2()
    {
        $types = new AcceptTypes(['HTTP_ACCEPT' => "application/javascript,text/*;q=0.9"]);
        $this->assertEquals('application/javascript', $types->preferred(['text/css', 'text/html', 'application/javascript', '', null, ' ']));
        $this->assertEquals('text/html', $types->preferred(['image/svg+xml', 'text/html', 'application/xml', '', null, ' ']));
        $this->assertNull($types->preferred(['application/xml', 'application/json']));
        $this->assertNull($types->preferred([]));
    }
}
