<?php
declare(strict_types=1);
/**
 * Caridea
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 * @copyright 2015-2018 LibreWorks contributors
 * @license   Apache-2.0
 */
namespace Caridea\Http;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-04 at 17:06:57.
 */
class PaginationTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @covers Caridea\Http\Pagination
     */
    public function testBasic()
    {
        $object = new Pagination(25, 30, ['foo' => false, 'bar' => true]);
        $this->assertSame(25, $object->getMax());
        $this->assertSame(30, $object->getOffset());
        $this->assertEquals(['foo' => false, 'bar' => true], $object->getOrder());
    }

    /**
     * @covers Caridea\Http\Pagination
     */
    public function testBad()
    {
        $object = new Pagination(PHP_INT_MAX, -1, ['  ' => 'aoeu', 'bar' => 1, 'baz' => 'yes']);
        $this->assertSame(PHP_INT_MAX, $object->getMax());
        $this->assertSame(0, $object->getOffset());
        $this->assertEquals(['bar' => false, 'baz' => false], $object->getOrder());
    }
}
