<?php
/**
 * Caridea
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 * @copyright 2015 LibreWorks contributors
 * @license   http://opensource.org/licenses/Apache-2.0 Apache 2.0 License
 */
namespace Caridea\Http;

/**
 * An implementation of Problem Details for HTTP APIs.
 *
 * Unfortunately, the specific draft of the memo is expired as of March.
 * Hopefully a new version will be released soon.
 *
 * @copyright 2015 LibreWorks contributors
 * @license   http://opensource.org/licenses/Apache-2.0 Apache 2.0 License
 * @see https://tools.ietf.org/html/draft-ietf-appsawg-http-problem-00
 */
class ProblemDetails
{
    const MIME_TYPE_JSON = 'application/problem+json';
    const REGEX_NAMES = '/^[a-z][a-z0-9_]{2,}$/i';
    
    /**
     * @var \Psr\Http\Message\UriInterface An absolute URI that identifies the problem type
     */
    protected $type;
    /**
     * @var string A short, human-readable summary of the problem type
     */
    protected $title;
    /**
     * @var int The HTTP status code generated by the origin server for this occurrence of the problem
     */
    protected $status;
    /**
     * @var string A human-readable explanation specific to this occurrence of the problem
     */
    protected $detail;
    /**
     * @var \Psr\Http\Message\UriInterface An absolute URI that identifies the specific occurrence of the problem
     */
    protected $instance;
    /**
     * @var array Map of `string` names to `mixed` values
     */
    protected $extensions = [];
    /**
     * @var array Cached output
     */
    protected $output;

    /**
     * Creates a new ProblemDetails.
     *
     * The `extensions` parameter, if provided, must be an associative array
     * matching names to values. Each name must follow the guidelines in the
     * RFC, namely start with a letter, be at least three characters long, and
     * only contain alpha, digit, and the underscore. The values can be of any
     * type, but be aware that the values must be easily converted to JSON. You
     * pretty much always want these values to be immutable.
     *
     * @param \Psr\Http\Message\UriInterface $type An absolute URI that identifies the problem type
     * @param string $title A short, human-readable summary of the problem type
     * @param int $status The HTTP status code generated by the origin server for this occurrence of the problem
     * @param string $detail A human-readable explanation specific to this occurrence of the problem
     * @param \Psr\Http\Message\UriInterface $instance An absolute URI that identifies the specific occurrence of the problem
     * @param array $extensions Additional members to the ProblemDetails
     */
    public function __construct(\Psr\Http\Message\UriInterface $type = null, $title = null, $status = 0, $detail = null, \Psr\Http\Message\UriInterface $instance = null, array $extensions = [])
    {
        $this->type = $type;
        $this->title = $title;
        $this->status = (int)$status;
        $this->detail = $detail;
        $this->instance = $instance;
        array_walk($extensions, function ($v, $k) {
            if (!preg_match(self::REGEX_NAMES, $k) || property_exists($this, $k)) {
                throw new \InvalidArgumentException("Invalid extension name: '$k'");
            }
        });
        $this->extensions = $extensions;
    }
    
    /**
     * Gets the absolute URI that identifies the problem type
     *
     * @return \Psr\Http\Message\UriInterface The problem type URI (or null)
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Gets the short, human-readable summary of the problem type.
     *
     * @return string A summary of the problem type
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Gets the HTTP status code generated by the origin server for this occurrence of the problem
     *
     * @return int The status code
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Gets a human readable explanation specific to this occurrence of the problem.
     *
     * @return string An explanation specific to this occurrence of the problem
     */
    public function getDetail()
    {
        return $this->detail;
    }

    /**
     * Gets the absolute URI that identifies the specific occurrence of the problem.
     *
     * @return \Psr\Http\Message\UriInterface The URI that identifies the specific occurrence of the problem (or null)
     */
    public function getInstance()
    {
        return $this->instance;
    }

    /**
     * Gets an array of any extension members defined.
     *
     * @return array Any extension members, never null.
     */
    public function getExtensions()
    {
        return $this->extensions;
    }

    /**
     * Returns a JSON representation of this problem.
     *
     * @return string The JSON representation
     */
    public function __toString()
    {
        return $this->toJson();
    }

    /**
     * A JSON representation of this problem.
     *
     * @return string The JSON representation
     */
    public function toJson()
    {
        return json_encode($this->toArray());
    }

    /**
     * Gets a serializable representation of this problem.
     *
     * @return array This problem detail as an associative array
     */
    public function toArray()
    {
        if (!$this->output) {
            $problem = [
                'type' => $this->type ? (string)$this->type : 'about:blank'
            ];
            if ($this->title) {
                $problem['title'] = $this->title;
            }
            if ($this->status) {
                $problem['status'] = $this->status;
            }
            if ($this->detail) {
                $problem['detail'] = $this->detail;
            }
            if ($this->instance) {
                $problem['instance'] = (string)$this->instance;
            }
            $this->output = array_merge($problem, $this->extensions);
        }
        return $this->output;
    }
}
